// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DiscoveredPeerInfo`, `FfiTransferEvent`, `MDNS`, `RUNTIME`, `TRANSPORT_MANAGER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `deref`, `deref`, `fmt`, `fmt`, `initialize`, `initialize`, `initialize`

Future<String> initPeer({required String deviceName}) =>
    RustLib.instance.api.crateApiInitPeer(deviceName: deviceName);

Stream<String> startDiscovery() =>
    RustLib.instance.api.crateApiStartDiscovery();

Future<void> advertisePeer(
        {required String peerId,
        required String deviceName,
        required int port}) =>
    RustLib.instance.api.crateApiAdvertisePeer(
        peerId: peerId, deviceName: deviceName, port: port);

Stream<String> startQrReceiver(
        {required String deviceName, required String outputDir}) =>
    RustLib.instance.api
        .crateApiStartQrReceiver(deviceName: deviceName, outputDir: outputDir);

Stream<String> connectToQr(
        {required String qrJson, required String filePath}) =>
    RustLib.instance.api
        .crateApiConnectToQr(qrJson: qrJson, filePath: filePath);
