name: swiftbeam
description: Cross-platform P2P file transfer client.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_rust_bridge: 2.12.0
  uuid: ^4.3.3
  freezed_annotation: ^2.4.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2
  flutter_blue_plus: ^1.31.0
  file_picker: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.2
  rust_lib_swiftbeam:
    path: rust_builder
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
  integration_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/



